// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(SaplingCoreFFI)
import SaplingCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sapling_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sapling_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSaplingInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Main entry point exposed to Swift/Kotlin via UniFFI.
 */
public protocol SaplingCoreProtocol: AnyObject, Sendable {
    
    func addLocation(point: FfiTrackPoint) throws  -> FfiRecordingUpdate?
    
    func createGem(input: FfiCreateGemInput) throws  -> FfiGem
    
    func getGem(id: String) throws  -> FfiGem?
    
    func getTrackPoints(tripId: String) throws  -> [FfiTrackPoint]
    
    func importGpx(filePath: String) throws  -> [FfiTrackPoint]
    
    func listGems() throws  -> [FfiGem]
    
    func searchGems(query: String) throws  -> [FfiGem]
    
    func startRecording(name: String?) throws  -> String
    
    func stopRecording() throws  -> FfiTripSummary?
    
}
/**
 * Main entry point exposed to Swift/Kotlin via UniFFI.
 */
open class SaplingCore: SaplingCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_sapling_fn_clone_saplingcore(self.pointer, $0) }
    }
public convenience init(dbPath: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_constructor_saplingcore_new(
        FfiConverterString.lower(dbPath),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_sapling_fn_free_saplingcore(pointer, $0) }
    }

    

    
open func addLocation(point: FfiTrackPoint)throws  -> FfiRecordingUpdate?  {
    return try  FfiConverterOptionTypeFfiRecordingUpdate.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_add_location(self.uniffiClonePointer(),
        FfiConverterTypeFfiTrackPoint_lower(point),$0
    )
})
}
    
open func createGem(input: FfiCreateGemInput)throws  -> FfiGem  {
    return try  FfiConverterTypeFfiGem_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_create_gem(self.uniffiClonePointer(),
        FfiConverterTypeFfiCreateGemInput_lower(input),$0
    )
})
}
    
open func getGem(id: String)throws  -> FfiGem?  {
    return try  FfiConverterOptionTypeFfiGem.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_get_gem(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func getTrackPoints(tripId: String)throws  -> [FfiTrackPoint]  {
    return try  FfiConverterSequenceTypeFfiTrackPoint.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_get_track_points(self.uniffiClonePointer(),
        FfiConverterString.lower(tripId),$0
    )
})
}
    
open func importGpx(filePath: String)throws  -> [FfiTrackPoint]  {
    return try  FfiConverterSequenceTypeFfiTrackPoint.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_import_gpx(self.uniffiClonePointer(),
        FfiConverterString.lower(filePath),$0
    )
})
}
    
open func listGems()throws  -> [FfiGem]  {
    return try  FfiConverterSequenceTypeFfiGem.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_list_gems(self.uniffiClonePointer(),$0
    )
})
}
    
open func searchGems(query: String)throws  -> [FfiGem]  {
    return try  FfiConverterSequenceTypeFfiGem.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_search_gems(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
open func startRecording(name: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_start_recording(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(name),$0
    )
})
}
    
open func stopRecording()throws  -> FfiTripSummary?  {
    return try  FfiConverterOptionTypeFfiTripSummary.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_sapling_fn_method_saplingcore_stop_recording(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSaplingCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SaplingCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SaplingCore {
        return SaplingCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SaplingCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SaplingCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SaplingCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSaplingCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> SaplingCore {
    return try FfiConverterTypeSaplingCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSaplingCore_lower(_ value: SaplingCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSaplingCore.lower(value)
}




public struct FfiCreateGemInput {
    public var gemType: FfiGemType
    public var title: String
    public var notes: String?
    public var latitude: Double
    public var longitude: Double
    public var elevation: Double?
    public var confidence: UInt8
    public var tags: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(gemType: FfiGemType, title: String, notes: String?, latitude: Double, longitude: Double, elevation: Double?, confidence: UInt8, tags: [String]) {
        self.gemType = gemType
        self.title = title
        self.notes = notes
        self.latitude = latitude
        self.longitude = longitude
        self.elevation = elevation
        self.confidence = confidence
        self.tags = tags
    }
}

#if compiler(>=6)
extension FfiCreateGemInput: Sendable {}
#endif


extension FfiCreateGemInput: Equatable, Hashable {
    public static func ==(lhs: FfiCreateGemInput, rhs: FfiCreateGemInput) -> Bool {
        if lhs.gemType != rhs.gemType {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.latitude != rhs.latitude {
            return false
        }
        if lhs.longitude != rhs.longitude {
            return false
        }
        if lhs.elevation != rhs.elevation {
            return false
        }
        if lhs.confidence != rhs.confidence {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(gemType)
        hasher.combine(title)
        hasher.combine(notes)
        hasher.combine(latitude)
        hasher.combine(longitude)
        hasher.combine(elevation)
        hasher.combine(confidence)
        hasher.combine(tags)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCreateGemInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCreateGemInput {
        return
            try FfiCreateGemInput(
                gemType: FfiConverterTypeFfiGemType.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                notes: FfiConverterOptionString.read(from: &buf), 
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf), 
                elevation: FfiConverterOptionDouble.read(from: &buf), 
                confidence: FfiConverterUInt8.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiCreateGemInput, into buf: inout [UInt8]) {
        FfiConverterTypeFfiGemType.write(value.gemType, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.notes, into: &buf)
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
        FfiConverterOptionDouble.write(value.elevation, into: &buf)
        FfiConverterUInt8.write(value.confidence, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCreateGemInput_lift(_ buf: RustBuffer) throws -> FfiCreateGemInput {
    return try FfiConverterTypeFfiCreateGemInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCreateGemInput_lower(_ value: FfiCreateGemInput) -> RustBuffer {
    return FfiConverterTypeFfiCreateGemInput.lower(value)
}


public struct FfiGem {
    public var id: String
    public var gemType: FfiGemType
    public var title: String
    public var notes: String?
    public var latitude: Double
    public var longitude: Double
    public var elevation: Double?
    public var confidence: UInt8
    public var tags: [String]
    public var createdAt: String
    public var updatedAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, gemType: FfiGemType, title: String, notes: String?, latitude: Double, longitude: Double, elevation: Double?, confidence: UInt8, tags: [String], createdAt: String, updatedAt: String) {
        self.id = id
        self.gemType = gemType
        self.title = title
        self.notes = notes
        self.latitude = latitude
        self.longitude = longitude
        self.elevation = elevation
        self.confidence = confidence
        self.tags = tags
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

#if compiler(>=6)
extension FfiGem: Sendable {}
#endif


extension FfiGem: Equatable, Hashable {
    public static func ==(lhs: FfiGem, rhs: FfiGem) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.gemType != rhs.gemType {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.latitude != rhs.latitude {
            return false
        }
        if lhs.longitude != rhs.longitude {
            return false
        }
        if lhs.elevation != rhs.elevation {
            return false
        }
        if lhs.confidence != rhs.confidence {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(gemType)
        hasher.combine(title)
        hasher.combine(notes)
        hasher.combine(latitude)
        hasher.combine(longitude)
        hasher.combine(elevation)
        hasher.combine(confidence)
        hasher.combine(tags)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiGem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiGem {
        return
            try FfiGem(
                id: FfiConverterString.read(from: &buf), 
                gemType: FfiConverterTypeFfiGemType.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                notes: FfiConverterOptionString.read(from: &buf), 
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf), 
                elevation: FfiConverterOptionDouble.read(from: &buf), 
                confidence: FfiConverterUInt8.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiGem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterTypeFfiGemType.write(value.gemType, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.notes, into: &buf)
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
        FfiConverterOptionDouble.write(value.elevation, into: &buf)
        FfiConverterUInt8.write(value.confidence, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGem_lift(_ buf: RustBuffer) throws -> FfiGem {
    return try FfiConverterTypeFfiGem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGem_lower(_ value: FfiGem) -> RustBuffer {
    return FfiConverterTypeFfiGem.lower(value)
}


public struct FfiRecordingUpdate {
    public var state: FfiActivityState
    public var distanceM: Double
    public var elevationGain: Double
    public var elapsedMs: Int64
    public var pointCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: FfiActivityState, distanceM: Double, elevationGain: Double, elapsedMs: Int64, pointCount: UInt32) {
        self.state = state
        self.distanceM = distanceM
        self.elevationGain = elevationGain
        self.elapsedMs = elapsedMs
        self.pointCount = pointCount
    }
}

#if compiler(>=6)
extension FfiRecordingUpdate: Sendable {}
#endif


extension FfiRecordingUpdate: Equatable, Hashable {
    public static func ==(lhs: FfiRecordingUpdate, rhs: FfiRecordingUpdate) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.distanceM != rhs.distanceM {
            return false
        }
        if lhs.elevationGain != rhs.elevationGain {
            return false
        }
        if lhs.elapsedMs != rhs.elapsedMs {
            return false
        }
        if lhs.pointCount != rhs.pointCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(distanceM)
        hasher.combine(elevationGain)
        hasher.combine(elapsedMs)
        hasher.combine(pointCount)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRecordingUpdate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRecordingUpdate {
        return
            try FfiRecordingUpdate(
                state: FfiConverterTypeFfiActivityState.read(from: &buf), 
                distanceM: FfiConverterDouble.read(from: &buf), 
                elevationGain: FfiConverterDouble.read(from: &buf), 
                elapsedMs: FfiConverterInt64.read(from: &buf), 
                pointCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRecordingUpdate, into buf: inout [UInt8]) {
        FfiConverterTypeFfiActivityState.write(value.state, into: &buf)
        FfiConverterDouble.write(value.distanceM, into: &buf)
        FfiConverterDouble.write(value.elevationGain, into: &buf)
        FfiConverterInt64.write(value.elapsedMs, into: &buf)
        FfiConverterUInt32.write(value.pointCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRecordingUpdate_lift(_ buf: RustBuffer) throws -> FfiRecordingUpdate {
    return try FfiConverterTypeFfiRecordingUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRecordingUpdate_lower(_ value: FfiRecordingUpdate) -> RustBuffer {
    return FfiConverterTypeFfiRecordingUpdate.lower(value)
}


/**
 * UniFFI record types — re-exported from core with UniFFI derives.
 */
public struct FfiTrackPoint {
    public var latitude: Double
    public var longitude: Double
    public var elevation: Double?
    public var hAccuracy: Double
    public var vAccuracy: Double
    public var speed: Double
    public var course: Double
    public var timestampMs: Int64
    public var baroRelativeAltitude: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(latitude: Double, longitude: Double, elevation: Double?, hAccuracy: Double, vAccuracy: Double, speed: Double, course: Double, timestampMs: Int64, baroRelativeAltitude: Double?) {
        self.latitude = latitude
        self.longitude = longitude
        self.elevation = elevation
        self.hAccuracy = hAccuracy
        self.vAccuracy = vAccuracy
        self.speed = speed
        self.course = course
        self.timestampMs = timestampMs
        self.baroRelativeAltitude = baroRelativeAltitude
    }
}

#if compiler(>=6)
extension FfiTrackPoint: Sendable {}
#endif


extension FfiTrackPoint: Equatable, Hashable {
    public static func ==(lhs: FfiTrackPoint, rhs: FfiTrackPoint) -> Bool {
        if lhs.latitude != rhs.latitude {
            return false
        }
        if lhs.longitude != rhs.longitude {
            return false
        }
        if lhs.elevation != rhs.elevation {
            return false
        }
        if lhs.hAccuracy != rhs.hAccuracy {
            return false
        }
        if lhs.vAccuracy != rhs.vAccuracy {
            return false
        }
        if lhs.speed != rhs.speed {
            return false
        }
        if lhs.course != rhs.course {
            return false
        }
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        if lhs.baroRelativeAltitude != rhs.baroRelativeAltitude {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(latitude)
        hasher.combine(longitude)
        hasher.combine(elevation)
        hasher.combine(hAccuracy)
        hasher.combine(vAccuracy)
        hasher.combine(speed)
        hasher.combine(course)
        hasher.combine(timestampMs)
        hasher.combine(baroRelativeAltitude)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTrackPoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTrackPoint {
        return
            try FfiTrackPoint(
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf), 
                elevation: FfiConverterOptionDouble.read(from: &buf), 
                hAccuracy: FfiConverterDouble.read(from: &buf), 
                vAccuracy: FfiConverterDouble.read(from: &buf), 
                speed: FfiConverterDouble.read(from: &buf), 
                course: FfiConverterDouble.read(from: &buf), 
                timestampMs: FfiConverterInt64.read(from: &buf), 
                baroRelativeAltitude: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTrackPoint, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
        FfiConverterOptionDouble.write(value.elevation, into: &buf)
        FfiConverterDouble.write(value.hAccuracy, into: &buf)
        FfiConverterDouble.write(value.vAccuracy, into: &buf)
        FfiConverterDouble.write(value.speed, into: &buf)
        FfiConverterDouble.write(value.course, into: &buf)
        FfiConverterInt64.write(value.timestampMs, into: &buf)
        FfiConverterOptionDouble.write(value.baroRelativeAltitude, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTrackPoint_lift(_ buf: RustBuffer) throws -> FfiTrackPoint {
    return try FfiConverterTypeFfiTrackPoint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTrackPoint_lower(_ value: FfiTrackPoint) -> RustBuffer {
    return FfiConverterTypeFfiTrackPoint.lower(value)
}


public struct FfiTripSummary {
    public var id: String
    public var name: String
    public var distanceM: Double
    public var elevationGain: Double
    public var elevationLoss: Double
    public var durationMs: Int64
    public var gemCount: UInt32
    public var segmentCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, distanceM: Double, elevationGain: Double, elevationLoss: Double, durationMs: Int64, gemCount: UInt32, segmentCount: UInt32) {
        self.id = id
        self.name = name
        self.distanceM = distanceM
        self.elevationGain = elevationGain
        self.elevationLoss = elevationLoss
        self.durationMs = durationMs
        self.gemCount = gemCount
        self.segmentCount = segmentCount
    }
}

#if compiler(>=6)
extension FfiTripSummary: Sendable {}
#endif


extension FfiTripSummary: Equatable, Hashable {
    public static func ==(lhs: FfiTripSummary, rhs: FfiTripSummary) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.distanceM != rhs.distanceM {
            return false
        }
        if lhs.elevationGain != rhs.elevationGain {
            return false
        }
        if lhs.elevationLoss != rhs.elevationLoss {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        if lhs.gemCount != rhs.gemCount {
            return false
        }
        if lhs.segmentCount != rhs.segmentCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(distanceM)
        hasher.combine(elevationGain)
        hasher.combine(elevationLoss)
        hasher.combine(durationMs)
        hasher.combine(gemCount)
        hasher.combine(segmentCount)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTripSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTripSummary {
        return
            try FfiTripSummary(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                distanceM: FfiConverterDouble.read(from: &buf), 
                elevationGain: FfiConverterDouble.read(from: &buf), 
                elevationLoss: FfiConverterDouble.read(from: &buf), 
                durationMs: FfiConverterInt64.read(from: &buf), 
                gemCount: FfiConverterUInt32.read(from: &buf), 
                segmentCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTripSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterDouble.write(value.distanceM, into: &buf)
        FfiConverterDouble.write(value.elevationGain, into: &buf)
        FfiConverterDouble.write(value.elevationLoss, into: &buf)
        FfiConverterInt64.write(value.durationMs, into: &buf)
        FfiConverterUInt32.write(value.gemCount, into: &buf)
        FfiConverterUInt32.write(value.segmentCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTripSummary_lift(_ buf: RustBuffer) throws -> FfiTripSummary {
    return try FfiConverterTypeFfiTripSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTripSummary_lower(_ value: FfiTripSummary) -> RustBuffer {
    return FfiConverterTypeFfiTripSummary.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiActivityState {
    
    case moving
    case paused
    case stopped
}


#if compiler(>=6)
extension FfiActivityState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiActivityState: FfiConverterRustBuffer {
    typealias SwiftType = FfiActivityState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiActivityState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .moving
        
        case 2: return .paused
        
        case 3: return .stopped
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiActivityState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .moving:
            writeInt(&buf, Int32(1))
        
        
        case .paused:
            writeInt(&buf, Int32(2))
        
        
        case .stopped:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActivityState_lift(_ buf: RustBuffer) throws -> FfiActivityState {
    return try FfiConverterTypeFfiActivityState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActivityState_lower(_ value: FfiActivityState) -> RustBuffer {
    return FfiConverterTypeFfiActivityState.lower(value)
}


extension FfiActivityState: Equatable, Hashable {}







/**
 * Error type exposed to foreign code via UniFFI.
 */
public enum FfiError: Swift.Error {

    
    
    case Database(msg: String
    )
    case NotFound(msg: String
    )
    case InvalidInput(msg: String
    )
    case Io(msg: String
    )
    case GpxParse(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Database(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotFound(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidInput(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .GpxParse(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Database(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .NotFound(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidInput(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Io(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .GpxParse(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}


extension FfiError: Equatable, Hashable {}




extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * UniFFI enum types — typed alternatives to String for gem types and activity states.
 */

public enum FfiGemType {
    
    case campsite
    case water
    case hazard
    case viewpoint
    case trailhead
    case junction
    case resupply
    case note
}


#if compiler(>=6)
extension FfiGemType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiGemType: FfiConverterRustBuffer {
    typealias SwiftType = FfiGemType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiGemType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .campsite
        
        case 2: return .water
        
        case 3: return .hazard
        
        case 4: return .viewpoint
        
        case 5: return .trailhead
        
        case 6: return .junction
        
        case 7: return .resupply
        
        case 8: return .note
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiGemType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .campsite:
            writeInt(&buf, Int32(1))
        
        
        case .water:
            writeInt(&buf, Int32(2))
        
        
        case .hazard:
            writeInt(&buf, Int32(3))
        
        
        case .viewpoint:
            writeInt(&buf, Int32(4))
        
        
        case .trailhead:
            writeInt(&buf, Int32(5))
        
        
        case .junction:
            writeInt(&buf, Int32(6))
        
        
        case .resupply:
            writeInt(&buf, Int32(7))
        
        
        case .note:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGemType_lift(_ buf: RustBuffer) throws -> FfiGemType {
    return try FfiConverterTypeFfiGemType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGemType_lower(_ value: FfiGemType) -> RustBuffer {
    return FfiConverterTypeFfiGemType.lower(value)
}


extension FfiGemType: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiGem: FfiConverterRustBuffer {
    typealias SwiftType = FfiGem?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiGem.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiGem.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiRecordingUpdate: FfiConverterRustBuffer {
    typealias SwiftType = FfiRecordingUpdate?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiRecordingUpdate.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiRecordingUpdate.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiTripSummary: FfiConverterRustBuffer {
    typealias SwiftType = FfiTripSummary?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiTripSummary.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiTripSummary.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiGem: FfiConverterRustBuffer {
    typealias SwiftType = [FfiGem]

    public static func write(_ value: [FfiGem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiGem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiGem] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiGem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiGem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiTrackPoint: FfiConverterRustBuffer {
    typealias SwiftType = [FfiTrackPoint]

    public static func write(_ value: [FfiTrackPoint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiTrackPoint.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiTrackPoint] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiTrackPoint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiTrackPoint.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sapling_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_add_location() != 4440) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_create_gem() != 16820) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_get_gem() != 6939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_get_track_points() != 27836) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_import_gpx() != 16505) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_list_gems() != 4708) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_search_gems() != 48905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_start_recording() != 46456) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_method_saplingcore_stop_recording() != 6314) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapling_checksum_constructor_saplingcore_new() != 24575) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSaplingInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all